[package]
name = "dano"
version = "0.3.2"
edition = "2021"
keywords = ["checksum", "verify", "media", "cli-utility", "storage"]
description = "A CLI tool for generating checksums of media bitstreams"
repository = "https://github.com/kimono-koans/dano"
readme = "README.md"
categories = [ "command-line-utilities",  "os" ]
license = "MPL-2.0"
documentation = "https://github.com/kimono-koans/dano/blob/master/README.md"

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
strip = true
opt-level = "z"  # Aggressively optimize for size.
lto = true

[dependencies]
clap = { version = "3.2.8", features = ["cargo"] }
rayon = { version = "1.5.1", default-features = false }
which = { version = "4.2.4", default-features = false }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83" } # need alloc or std
itertools = { version = "0.10.3" } # use_std, use_alloc for into_group_map_by()
crossbeam = { version = "0.8.2" } # default features includes channels
num_cpus = { version = "1.0", default-features = false }
xattr = { version = "0.2.3", default-features = false }
rug = { version = "1.17.0", features = ["serde"]  }


[package.metadata.deb]
maintainer = "kimono koans <https://github.com/kimono-koans/>"
copyright = "2022, Robert Swinford <robert.swinford<...at...>gmail.com>"
extended-description = """\
dano is a wrapper for ffmpeg that checksums the internal file streams of ffmpeg compatible media files, \
and stores them in a format which can be used to verify such checksums later.  \
This is handy, because, should you choose to change metadata tags, or change file names, \
the media checksums should remain the same.
"""
license-file = ["LICENSE", "4"]
depends = "ffmpeg (>=4.2.7), $auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/dano", "usr/bin/", "755"],
    ["dano.1", "usr/share/man/man1/", "644"],
    ["README.md", "usr/share/doc/dano/README", "644"],
]