[package]
name = "dano"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.8", features = ["cargo"] }
rayon = { version = "1.5.1", default-features = false }
which = { version = "4.2.4", default-features = false }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83" } # need alloc or std
itertools = { version = "0.10.3" } # use_std, use_alloc for into_group_map_by()
crossbeam = { version = "0.8.2" } # default features includes channels
num_cpus = { version = "1.0", default-features = false }
xattr = { version = "0.2.3", default-features = false }