[package]
name = "dano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["cargo"] }
rayon = { version = "1.5.1", default-features = false }
which = { version = "4.2.4", default-features = false }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"