name: Build Debian/Redhat packages

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
      # Allow manual triggering
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build  package with cargo-deb
      run: cargo deb --profile deb --separate-debug-symbols -- --locked
    - name: Install alien
      run: sudo apt-get install -y alien
    - name: Convert deb to rpm with alien
      working-directory: target/debian
      run: sudo alien --to-rpm dano_*.deb
    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      if: ${{startsWith(github.ref, 'refs/tags/') }}
      with:
          files: target/debian/dano*.*